# Support Python 3.10+.
target-version = "py310"
# Set the maximum line length to 79.
line-length = 79

[lint]
extend-select = [
  "F",  
  "E",  
  "W",  
  "C90",
  "I",
  "N",
  "D",
  "UP",
  "ISC", 
  "RUF"
]

ignore = ["D203", "D212", "RUF002"]